disabled: true
name: Add Supported Device
description: inform me of a supported device not currently known
title: "Add Supported Device: "
labels: device-support
assignees:
  - bloomkd46
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Supported Device Reguest!
        
  - type: input
    attributes:
      label: "Roomba Model:"
      description: "Without Any +'s"
      placeholder: i7
    validations:
      required: true
        
  - type: dropdown
    id: supported
    validations:
      required: true
    attributes:
      label: Did It Work
      description: "If It Didn't Work Don't Check The Box Below"
      options:
        - "This Plug-in Worked For My Roomba"
        - "This Plug-in didn't work for my roomba"
