# This is a basic workflow to help you get started with Actions

name: Add Supported Device To Readme

# Controls when the workflow will run
on:
  issues:
    types: opened
concurrency: 'main'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-Readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-supported-device.yml

      - run: |
          x=`echo ${{ steps.issue-parser.outputs.jsonString }}`
          echo "$x" > device.json
      - run: grep -Po '"'"supported"'"\s*:\s*"\K([^"]*)' device.json
      - run: grep -Po '"'"roomba_model"'"\s*:\s*"\K([^"]*)' device.json
